spin_manifest_version = 2

[application]
name = "bartholomew-template"
version = "0.1.0"
description = "Your new Bartholomew website."

[application.trigger.http]
base = "/"

[[trigger.http]]
id = "trigger-bartholomew"
component = "bartholomew"
route = "/..."

[[trigger.http]]
id = "trigger-fileserver"
component = "fileserver"
route = "/static/..."

[component.bartholomew]
source = { url = "https://github.com/fermyon/bartholomew/releases/download/v0.10.0/bartholomew.wasm", digest = "sha256:4cac1f51bb6db7ae8926733a8f106bb6d8f9a7938cf839f7d0a4109bfc997465" }
files = ["content/**/*", "templates/*", "scripts/*", "config/*", "shortcodes/*"]
allowed_outbound_hosts = ["redis://*:*", "mysql://*:*", "postgres://*:*"]

[component.fileserver]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
files = [{ source = "static/", destination = "/" }]
allowed_outbound_hosts = ["redis://*:*", "mysql://*:*", "postgres://*:*"]
